### ISSUE TITLE
请问 operation::fun1[] 这个有什么用？

### ISSUE THREAD

**Issue by ifzm** [zq99299/spring-restdocs-example#1]
这个写法看着有点疑惑，也没查到相关资料

是否代表同时输出目录下的所有.adoc文件？但是看起来好像没效果

菜鸟学习过程中，希望大佬不吝赐教  ：)

**Comment by ifzm** [comment]
和您的程序比较后发现了问题，是我的配置有问题，感谢

**Comment by zq99299** [comment]
哈，解决了就好; 这个是配套笔记
https://blog.csdn.net/mr_zhuqiang/article/details/81132362
